### ISSUE TITLE
ESMification

### ISSUE THREAD

**Issue by benzBrake** [benzBrake/userChrome.js-Loader#1]
In about a year (Firefox 136, planned for March 2025), Firefox will completely remove support for ChromeUtils.import and similar APIs.

**Comment by 117649** [comment]
你问题是有些扩展选项窗口打不开了吧

**Comment by benzBrake** [comment]
> 你问题是有些扩展选项窗口打不开了吧

是的

**Comment by 117649** [comment]
原因和解法我的pr里都写了的……
